GET  http://localhost:5135/games
###
GET  http://localhost:5135/games/2

###

POST http://localhost:5135/games
Content-Type: application/json

{
    "name": "Minecraft",
    "genre": "Kids and Family",
    "price": 19.99,
    "releaseDate": "2011-11-18"
}